import type { Metadata } from "next";
// ✅ 1. Import ONLY the font you need
import { Luckiest_Guy } from "next/font/google";
import "./globals.css";

// ✅ 2. Initialize the font object
// This specific font from Google requires a weight to be specified.
const luckiestGuy = Luckiest_Guy({
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/*
        ✅ 3. Apply the font's className directly to the body.
        This handles everything for you: loading the font, creating the
        CSS, and applying the font-family.
      */}
      <body className={`${luckiestGuy.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}